# Generated by Django 4.1.1 on 2022-09-27 16:24

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='description',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2022, 9, 27, 16, 24, 29, 868805, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='picture',
            field=models.ImageField(default=datetime.datetime(2022, 9, 27, 16, 24, 38, 964559, tzinfo=datetime.timezone.utc), upload_to='images'),
            preserve_default=False,
        ),
    ]
