# Generated by Django 4.1.1 on 2022-09-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_socailmedialink_blogmodel_author_blogmodel_code_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='picture',
            field=models.ImageField(upload_to='portfolio'),
        ),
    ]
